static const char *gither_ui=
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkWindow\" id=\"window1\">"
"    <signal name=\"destroy\" handler=\"gtk_main_quit\"/>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"orientation\">vertical</property>"
"        <child>"
"          <object class=\"GtkMenuBar\" id=\"menubar1\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">_File</property>"
"                <property name=\"use_underline\">True</property>"
"                <child type=\"submenu\">"
"                  <object class=\"GtkMenu\" id=\"menu1\">"
"                    <property name=\"visible\">True</property>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menunew\">"
"                        <property name=\"label\">gtk-new</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menuopen\">"
"                        <property name=\"label\">gtk-open</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menusave\">"
"                        <property name=\"label\">gtk-save</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkSeparatorMenuItem\" id=\"separatormenuitem1\">"
"                        <property name=\"visible\">True</property>"
"                      </object>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menuquit\">"
"                        <property name=\"label\">gtk-quit</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem2\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">_Edit</property>"
"                <property name=\"use_underline\">True</property>"
"                <child type=\"submenu\">"
"                  <object class=\"GtkMenu\" id=\"menu2\">"
"                    <property name=\"visible\">True</property>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menurevert\">"
"                        <property name=\"label\">gtk-revert-to-saved</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem4\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">_Help</property>"
"                <property name=\"use_underline\">True</property>"
"                <child type=\"submenu\">"
"                  <object class=\"GtkMenu\" id=\"menu3\">"
"                    <property name=\"visible\">True</property>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menuhelp\">"
"                        <property name=\"label\">gtk-help</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkImageMenuItem\" id=\"menuabout\">"
"                        <property name=\"label\">gtk-about</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"use_underline\">True</property>"
"                        <property name=\"use_stock\">True</property>"
"                      </object>"
"                    </child>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkToolbar\" id=\"toolbar1\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkToolButton\" id=\"toolsave\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"tooltip_text\" translatable=\"yes\">Save Icons</property>"
"                <property name=\"use_underline\">True</property>"
"                <property name=\"stock_id\">gtk-save</property>"
"                <accelerator key=\"s\" signal=\"clicked\" modifiers=\"GDK_CONTROL_MASK\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"homogeneous\">True</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkToolButton\" id=\"toolrevert\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"tooltip_text\" translatable=\"yes\">Revert Selected Icon </property>"
"                <property name=\"use_underline\">True</property>"
"                <property name=\"stock_id\">gtk-revert-to-saved</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"homogeneous\">True</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkViewport\" id=\"viewport1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"resize_mode\">queue</property>"
"            <child>"
"              <object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"hscrollbar_policy\">automatic</property>"
"                <property name=\"vscrollbar_policy\">automatic</property>"
"                <child>"
"                  <object class=\"GtkIconView\" id=\"iconview1\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                    <property name=\"margin\">30</property>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkStatusbar\" id=\"statusbar1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"spacing\">2</property>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">3</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"  <object class=\"GtkListStore\" id=\"liststore1\"/>"
"</interface>";
static const char *gither_save_ui=
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkWindow\" id=\"window1\">"
"    <property name=\"title\" translatable=\"yes\">Save</property>"
"    <property name=\"default_width\">320</property>"
"    <property name=\"default_height\">260</property>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"border_width\">3</property>"
"        <property name=\"orientation\">vertical</property>"
"        <child>"
"          <object class=\"GtkLabel\" id=\"label1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"label\" translatable=\"yes\">Select Directory and Sizes</property>"
"          </object>"
"          <packing>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHBox\" id=\"hbox1\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkLabel\" id=\"label2\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"xpad\">10</property>"
"                <property name=\"label\" translatable=\"yes\">Directory: </property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkFileChooserButton\" id=\"filechooserbutton1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"action\">select-folder</property>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkFrame\" id=\"frame1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"label_xalign\">0</property>"
"            <property name=\"shadow_type\">etched-out</property>"
"            <child>"
"              <object class=\"GtkAlignment\" id=\"alignment1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"left_padding\">12</property>"
"                <child>"
"                  <object class=\"GtkVBox\" id=\"vbox2\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"orientation\">vertical</property>"
"                    <child>"
"                      <object class=\"GtkRadioButton\" id=\"radiobutton1\">"
"                        <property name=\"label\" translatable=\"yes\">default</property>"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"can_focus\">True</property>"
"                        <property name=\"receives_default\">False</property>"
"                        <property name=\"tooltip_text\" translatable=\"yes\">Saves same size as reference icon set</property>"
"                        <property name=\"active\">True</property>"
"                        <property name=\"draw_indicator\">True</property>"
"                      </object>"
"                      <packing>"
"                        <property name=\"expand\">False</property>"
"                        <property name=\"position\">0</property>"
"                      </packing>"
"                    </child>"
"                    <child>"
"                      <object class=\"GtkHBox\" id=\"hbox2\">"
"                        <property name=\"visible\">True</property>"
"                        <property name=\"spacing\">5</property>"
"                        <child>"
"                          <object class=\"GtkRadioButton\" id=\"radiobutton2\">"
"                            <property name=\"label\" translatable=\"yes\">custom</property>"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"can_focus\">True</property>"
"                            <property name=\"receives_default\">False</property>"
"                            <property name=\"draw_indicator\">True</property>"
"                            <property name=\"group\">radiobutton1</property>"
"                          </object>"
"                          <packing>"
"                            <property name=\"expand\">False</property>"
"                            <property name=\"position\">0</property>"
"                          </packing>"
"                        </child>"
"                        <child>"
"                          <object class=\"GtkFileChooserButton\" id=\"filechooserbutton2\">"
"                            <property name=\"visible\">True</property>"
"                            <property name=\"sensitive\">False</property>"
"                            <property name=\"create_folders\">False</property>"
"                            <property name=\"show_hidden\">True</property>"
"                          </object>"
"                          <packing>"
"                            <property name=\"position\">1</property>"
"                          </packing>"
"                        </child>"
"                      </object>"
"                      <packing>"
"                        <property name=\"position\">1</property>"
"                      </packing>"
"                    </child>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"            <child type=\"label\">"
"              <object class=\"GtkLabel\" id=\"label3\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">&lt;b&gt;Size&lt;/b&gt;</property>"
"                <property name=\"use_markup\">True</property>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHSeparator\" id=\"hseparator1\">"
"            <property name=\"visible\">True</property>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"padding\">3</property>"
"            <property name=\"position\">3</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"spacing\">5</property>"
"            <property name=\"layout_style\">end</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button1\">"
"                <property name=\"label\">gtk-cancel</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"                <signal name=\"clicked\" handler=\"gtk_widget_destroy\" object=\"window1\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button2\">"
"                <property name=\"label\">gtk-save</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">4</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"  <object class=\"GtkFileFilter\" id=\"filefilter1\"/>"
"</interface>";
static const char *gither_open_ui=
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkDialog\" id=\"dialog1\">"
"    <property name=\"border_width\">5</property>"
"    <property name=\"default_width\">320</property>"
"    <property name=\"default_height\">175</property>"
"    <property name=\"type_hint\">normal</property>"
"    <property name=\"has_separator\">False</property>"
"    <child internal-child=\"vbox\">"
"      <object class=\"GtkVBox\" id=\"dialog-vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"orientation\">vertical</property>"
"        <property name=\"spacing\">2</property>"
"        <child>"
"          <object class=\"GtkHBox\" id=\"hbox1\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkLabel\" id=\"label1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">Theme:   </property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkComboBox\" id=\"combobox1\">"
"                <property name=\"visible\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHBox\" id=\"hbox2\">"
"            <property name=\"visible\">True</property>"
"            <child>"
"              <object class=\"GtkLabel\" id=\"label2\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"label\" translatable=\"yes\">Context:</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkComboBox\" id=\"combobox2\">"
"                <property name=\"visible\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"        <child internal-child=\"action_area\">"
"          <object class=\"GtkHButtonBox\" id=\"dialog-action_area1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"layout_style\">end</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button1\">"
"                <property name=\"label\">gtk-cancel</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"                <signal name=\"clicked\" handler=\"gtk_widget_destroy\" object=\"dialog1\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button2\">"
"                <property name=\"label\">gtk-ok</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"pack_type\">end</property>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"    <action-widgets>"
"      <action-widget response=\"0\">button1</action-widget>"
"      <action-widget response=\"0\">button2</action-widget>"
"    </action-widgets>"
"  </object>"
"</interface>";
static const char *gither_new_ui=
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkWindow\" id=\"window1\">"
"    <property name=\"width_request\">230</property>"
"    <property name=\"height_request\">170</property>"
"    <property name=\"title\" translatable=\"yes\">New</property>"
"    <property name=\"resizable\">False</property>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"border_width\">5</property>"
"        <property name=\"orientation\">vertical</property>"
"        <child>"
"          <object class=\"GtkRadioButton\" id=\"radiobutton1\">"
"            <property name=\"label\" translatable=\"yes\">Method One</property>"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">True</property>"
"            <property name=\"receives_default\">False</property>"
"            <property name=\"active\">True</property>"
"            <property name=\"draw_indicator\">True</property>"
"          </object>"
"          <packing>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkRadioButton\" id=\"radiobutton2\">"
"            <property name=\"label\" translatable=\"yes\">Method Two</property>"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">True</property>"
"            <property name=\"receives_default\">False</property>"
"            <property name=\"draw_indicator\">True</property>"
"            <property name=\"group\">radiobutton1</property>"
"          </object>"
"          <packing>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHSeparator\" id=\"hseparator1\">"
"            <property name=\"visible\">True</property>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"padding\">3</property>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"layout_style\">end</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button1\">"
"                <property name=\"label\">gtk-ok</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"padding\">3</property>"
"            <property name=\"position\">3</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>";
static const char *gither_help_ui=
"<interface>"
"  <requires lib=\"gtk+\" version=\"2.16\"/>"
"  <!-- interface-naming-policy project-wide -->"
"  <object class=\"GtkWindow\" id=\"window1\">"
"    <property name=\"border_width\">5</property>"
"    <property name=\"default_width\">450</property>"
"    <property name=\"default_height\">350</property>"
"    <child>"
"      <object class=\"GtkVBox\" id=\"vbox1\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"orientation\">vertical</property>"
"        <property name=\"spacing\">5</property>"
"        <child>"
"          <object class=\"GtkViewport\" id=\"viewport1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"resize_mode\">queue</property>"
"            <child>"
"              <object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"hscrollbar_policy\">automatic</property>"
"                <property name=\"vscrollbar_policy\">automatic</property>"
"                <child>"
"                  <object class=\"GtkTextView\" id=\"textview1\">"
"                    <property name=\"visible\">True</property>"
"                    <property name=\"can_focus\">True</property>"
"                  </object>"
"                </child>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHSeparator\" id=\"hseparator1\">"
"            <property name=\"visible\">True</property>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class=\"GtkHButtonBox\" id=\"hbuttonbox1\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"layout_style\">end</property>"
"            <child>"
"              <object class=\"GtkButton\" id=\"button1\">"
"                <property name=\"label\">gtk-close</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">True</property>"
"                <property name=\"receives_default\">True</property>"
"                <property name=\"use_stock\">True</property>"
"                <signal name=\"clicked\" handler=\"gtk_widget_destroy\" object=\"window1\"/>"
"              </object>"
"              <packing>"
"                <property name=\"expand\">False</property>"
"                <property name=\"fill\">False</property>"
"                <property name=\"position\">0</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"position\">2</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>";
